unit uConsultaIFood;

{*******************************************************************************
    Generated By   : JsonToDelphiClass - 0.65 
    Project link   : https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
    Generated On   : 2018-02-19 09:18:51

    Created By     : Petar Georgiev - 2014 (http://pgeorgiev.com) 
    Adapted Web By : Marlon Nardi - 2016 (http://jsontodelphi.com)
*******************************************************************************}

interface

uses Generics.Collections, Rest.Json;

type

TPedidoClass = class
private
  FCode: String;
  FCorrelationId: String;
  FCreatedAt: String;
  FId: String;
public
  property code: String read FCode write FCode;
  property correlationId: String read FCorrelationId write FCorrelationId;
  property createdAt: String read FCreatedAt write FCreatedAt;
  property id: String read FId write FId;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TPedidoClass;
end;

TDadospedidoClass = class
private
  FPedido: TArray<TPedidoClass>;
public
  property pedido: TArray<TPedidoClass> read FPedido write FPedido;
  destructor Destroy; override;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TDadospedidoClass;
end;

TRootClass = class
private
  FDadospedido: TDadospedidoClass;
public
  property dadospedido: TDadospedidoClass read FDadospedido write FDadospedido;
  constructor Create;
  destructor Destroy; override;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TRootClass;
end;

implementation

{TPedidoClass}


function TPedidoClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TPedidoClass.FromJsonString(AJsonString: string): TPedidoClass;
begin
  result := TJson.JsonToObject<TPedidoClass>(AJsonString)
end;

{TDadospedidoClass}

destructor TDadospedidoClass.Destroy;
var
  LpedidoItem: TPedidoClass;
begin

 for LpedidoItem in FPedido do
   LpedidoItem.Free;

  inherited;
end;

function TDadospedidoClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TDadospedidoClass.FromJsonString(AJsonString: string): TDadospedidoClass;
begin
  result := TJson.JsonToObject<TDadospedidoClass>(AJsonString)
end;

{TRootClass}

constructor TRootClass.Create;
begin
  inherited;
  FDadospedido := TDadospedidoClass.Create();
end;

destructor TRootClass.Destroy;
begin
  FDadospedido.Free;
  inherited;
end;

function TRootClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TRootClass.FromJsonString(AJsonString: string): TRootClass;
begin
  result := TJson.JsonToObject<TRootClass>(AJsonString)
end;

end.
