program EliteFood;

uses
  Forms,
  SysUtils,
  uMenu in 'uMenu.pas' {frmMenu},
  uLogin in 'uLogin.pas' {frmLogin},
  Vcl.Themes,
  Vcl.Styles,
  uServidor in 'uServidor.pas' {frmServidor},
  uConfiguracao in 'uConfiguracao.pas' {frmConfiguracao},
  UPrinters in 'Geral\UPrinters.pas',
  uControleMesa in 'uControleMesa.pas' {frmControleMesa},
  uConfirmacaoSenha in 'uConfirmacaoSenha.pas' {frmConfirmacaoSenha},
  uControleMesaItensAcoes in 'uControleMesaItensAcoes.pas' {frmControleMesaItensAcoes},
  uBuscaRegistro in 'uBuscaRegistro.pas' {frmBuscaRegistro},
  uControleMesaRenomear in 'uControleMesaRenomear.pas' {frmControleMesaRenomear},
  uControleMesaReservar in 'uControleMesaReservar.pas' {frmControleMesaReservar},
  uControleMesaJuntarTransferir in 'uControleMesaJuntarTransferir.pas' {frmControleMesaJuntarTransferir},
  uPosPrinterConfiguraSerial in 'uPosPrinterConfiguraSerial.pas' {frConfiguraSerial},
  uPosPrinterTeste in 'uPosPrinterTeste.pas' {FrmPosPrinterConfig},
  uControleMesaFechamento in 'uControleMesaFechamento.pas' {frmControleMesaFechamento},
  uCaixaAberturaFechamento in 'uCaixaAberturaFechamento.pas' {frmCaixaAberturaFechamento},
  uControleMesaPessoas in 'uControleMesaPessoas.pas' {frmControleMesaPessoas},
  uCaixaStatus in 'uCaixaStatus.pas' {frmCaixaStatus},
  uCaixaLancaMovimento in 'uCaixaLancaMovimento.pas' {frmCaixaLancaMovimento},
  uComunicadorServerSAT in 'Geral\uComunicadorServerSAT.pas',
  uGeradorSAT in 'Geral\uGeradorSAT.pas',
  uDetalheProduto in 'Detalhes\uDetalheProduto.pas' {frmDetalheProduto},
  uConsUsuarios in 'uConsUsuarios.pas' {frmConsUsuarios},
  uMovimentoEstoque in 'uMovimentoEstoque.pas' {frmMovimentoEstoque},
  uFechamentoMesaComanda in 'uFechamentoMesaComanda.pas' {frmFechamentoMesaComanda},
  uConsProduto in 'Consultas\uConsProduto.pas' {frmConsProduto},
  uDetalheUsuario in 'Detalhes\uDetalheUsuario.pas' {frmDetalheUsuario},
  uRelatorioVendas in 'Relatorios\uRelatorioVendas.pas' {frmRelatorioVendas},
  untConstSAT in 'Geral\untConstSAT.pas',
  uChamaFiscal in 'uChamaFiscal.pas' {frmChamaFiscal},
  uDetalheCliente in 'detalhes\uDetalheCliente.pas' {frmDetalheCliente},
  uControleDelivery in 'uControleDelivery.pas' {frmControleDelivery},
  uControleDeliveryDetalheVenda in 'uControleDeliveryDetalheVenda.pas' {frmControleDeliveryDetalheVenda},
  uControleDeliveryFinaliza in 'uControleDeliveryFinaliza.pas' {frmControleDeliveryFinaliza},
  uControleDeliveryFechamento in 'uControleDeliveryFechamento.pas' {frmControleDeliveryFechamento},
  uControleDeliverySelecaoEntregador in 'uControleDeliverySelecaoEntregador.pas' {frmControleDeliverySelecaoEntregador},
  uFrmModelo in 'uFrmModelo.pas' {frmModelo},
  ufrmModeloConsulta in 'ufrmModeloConsulta.pas' {frmModeloConsulta},
  ufrmModeloConsultaTabelaUnica in 'ufrmModeloConsultaTabelaUnica.pas' {frmModeloConsultaTabelaUnica},
  uConsCliente in 'uConsCliente.pas' {frmConsCliente},
  uDetalheClienteMovimentoConta in 'uDetalheClienteMovimentoConta.pas' {frmDetalheClienteMovimentoConta},
  uConsBairro in 'uConsBairro.pas' {frmConsBairro},
  uDetalheBairro in 'uDetalheBairro.pas' {frmDetalheBairro},
  uModeloCadastroSimples in 'uModeloCadastroSimples.pas' {frmModeloCadastroSimples},
  uDetalheComposicao in 'Detalhes\uDetalheComposicao.pas' {frmDetalheComposicao},
  uConsComposicao in 'Consultas\uConsComposicao.pas' {frmConsComposicao},
  Funcao_DB in 'Geral\Funcao_DB.pas',
  Funcoes_XE in 'Geral\Funcoes_XE.pas',
  Traducoes in 'Geral\Traducoes.pas',
  uFuncoes in 'Geral\uFuncoes.pas',
  uPadrao in 'Geral\uPadrao.pas' {frmPadrao},
  uPadraoCons in 'Geral\uPadraoCons.pas' {frmPadraoCons},
  uPadraoDetalhe in 'Geral\uPadraoDetalhe.pas' {frmPadraoDetalhe},
  uMemo in 'uMemo.pas' {frmMemo},
  uGraficoVendas in 'uGraficoVendas.pas' {frmGraficoVendas},
  uRelatorioEstoque in 'Relatorios\uRelatorioEstoque.pas' {frmRelatorioEstoque},
  uConsVendaSAT in 'uConsVendaSAT.pas' {frmConsVendaSAT},
  uVendaSelecaoTamanho in 'uVendaSelecaoTamanho.pas' {frmVendaSelecaoTamanho},
  uVendaItemFracionado in 'uVendaItemFracionado.pas' {frmVendaItemFracionado},
  uDetalheOpcional in 'uDetalheOpcional.pas' {frmDetalheOpcional},
  uConsOpcionais in 'uConsOpcionais.pas' {frmConsOpcionais},
  uConsMesa in 'uConsMesa.pas' {frmConsMesa},
  uPDV in 'uPDV.pas' {frmPDV},
  uPDVFechamento in 'uPDVFechamento.pas' {frmPDVFechamento},
  uReimprimirCancelarCupom in 'uReimprimirCancelarCupom.pas' {frmReimpressaoCupom},
  uPDVCliente in 'uPDVCliente.pas' {frmPDVCliente},
  uVendaSelecaoPreco in 'uVendaSelecaoPreco.pas' {frmVendaSelecaoPreco},
  uVendaBalcaoTouch in 'uVendaBalcaoTouch.pas' {frmVendaBalcaoTouch},
  uDetalheFornecedor in 'uDetalheFornecedor.pas' {frmDetalheFornecedor},
  uConsFornecedor in 'uConsFornecedor.pas' {frmConsFornecedor},
  uDetalheConta in 'uDetalheConta.pas' {frmDetalheConta},
  uConsConta in 'uConsConta.pas' {frmConsConta},
  uControleContasPagar in 'uControleContasPagar.pas' {frmControleContasPagar},
  uContasPagarInclusao in 'uContasPagarInclusao.pas' {frmContasPagarInclusao},
  uContasPagarPagamento in 'uContasPagarPagamento.pas' {frmContasPagarPagamento},
  uDetalheContaCorrente in 'uDetalheContaCorrente.pas' {frmDetalheContaCorrente},
  uConsContaCorrente in 'uConsContaCorrente.pas' {frmConsContaCorrente},
  uControleContasPagarEditar in 'uControleContasPagarEditar.pas' {frmControleContasPagarEditar},
  uControleMesaImpressaoCozinha in 'uControleMesaImpressaoCozinha.pas' {frmControleMesaImpressaoCozinha},
  uRelatorioHistoricoVendasCliente in 'Relatorios\uRelatorioHistoricoVendasCliente.pas' {frmRelatorioHistoricoVendasCliente},
  uDetalheFormaPgto in 'Detalhes\uDetalheFormaPgto.pas' {frmDetalheFormaPgto},
  uConsFormaPgto in 'Consultas\uConsFormaPgto.pas' {frmConsFormaPgto},
  uNovaSenha in 'uNovaSenha.pas' {frmNovaSenha},
  uConsUnidade in 'uConsUnidade.pas' {frmConsUnidade},
  uDetalheUnidade in 'uDetalheUnidade.pas' {frmDetalheUnidade},
  uControleContasReceberFiado in 'uControleContasReceberFiado.pas' {frmControleContasReceberFiado},
  uContasReceberFiadoPagamento in 'uContasReceberFiadoPagamento.pas' {frmContasReceberFiadoPagamento},
  uConsCategoria in 'Consultas\uConsCategoria.pas' {frmConsCategoria},
  uDetalheCategoria in 'Detalhes\uDetalheCategoria.pas' {frmDetalheCategoria},
  uVendaTouch in 'uVendaTouch.pas' {frmVendaTouch},
  uVendaTouchAbertura in 'uVendaTouchAbertura.pas' {frmVendaTouchAbertura},
  uVendaTouchInsercao in 'uVendaTouchInsercao.pas' {frmVendaTouchInsercao},
  uControleMesaRelatorios in 'uControleMesaRelatorios.pas' {frmControleMesaRelatorios},
  uProdutoDuplicar in 'uProdutoDuplicar.pas' {frmProdutoDuplicar},
  uProdutoReajustePreco in 'uProdutoReajustePreco.pas' {frmProdutoReajustePreco},
  uDetalheCondicaoPagamento in 'uDetalheCondicaoPagamento.pas' {frmDetalheCondicaoPagamento},
  uConsCondicaoPagamento in 'uConsCondicaoPagamento.pas' {frmConsCondicaoPagamento},
  uRelatorioMovimentoContaCliente in 'uRelatorioMovimentoContaCliente.pas' {frmRelatorioMovimentoContaCliente},
  uVendaBalcao in 'uVendaBalcao.pas' {frmVendaBalcao},
  uVendaFiadoCrediario in 'uVendaFiadoCrediario.pas' {frmVendaFiadoCrediario},
  uRelatorioAniversariantes in 'uRelatorioAniversariantes.pas' {frmRelatorioAniversariantes},
  uControleDeliveryVendaAnterior in 'uControleDeliveryVendaAnterior.pas' {frmControleDeliveryVendaAnterior},
  uLiberacao in 'liberacao\uLiberacao.pas' {frmLiberacao},
  uSocketPing in 'liberacao\uSocketPing.pas',
  uEnvioEmailThread in 'Geral\uEnvioEmailThread.pas',
  uEnvioCFe in 'uEnvioCFe.pas' {frmEnvioCFe},
  uControleDevolucaoDevolucaoItens in 'uControleDevolucaoDevolucaoItens.pas' {frmControleDevolucaoDevolucaoItens},
  uControleDevolucaoFechamento in 'uControleDevolucaoFechamento.pas' {frmControleDevolucaoFechamento},
  uGeradorNFCe in 'Geral\uGeradorNFCe.pas',
  uLogAparelhoSAT in 'uLogAparelhoSAT.pas' {frmLogAparelho},
  uInutilizacaoNFCe in 'uInutilizacaoNFCe.pas' {frmInutilizacaoNFCe},
  uEnvioEmail in 'uEnvioEmail.pas' {frmEnvioEmail},
  uVendaSelecaoVendedor in 'uVendaSelecaoVendedor.pas' {frmVendaSelecaoVendedor},
  uRelatorioABC in 'Relatorios\uRelatorioABC.pas' {frmRelatorioABC},
  uRelatorioABCPagamentos in 'uRelatorioABCPagamentos.pas' {frmRelatorioABCPagamentos},
  uGeradorECF in 'Geral\uGeradorECF.pas',
  uPDVMenuFiscal in 'uPDVMenuFiscal.pas' {frmPDVMenuFiscalECF},
  uTransferenciaiten in 'uTransferenciaiten.pas' {frmTransferenciaitem},
  uControleMesaUtilitarios in 'uControleMesaUtilitarios.pas' {frmControleMesaUtilitarios},
  uControleMesaUtilitariosBalanca in 'uControleMesaUtilitariosBalanca.pas' {frmControleMesaUtilitariosBalanca},
  uControleMesaJuntar in 'uControleMesaJuntar.pas' {frmControleMesaJuntar},
  uVinculacaomesaeambiente in 'uVinculacaomesaeambiente.pas' {frmVinculacaomesaeambiente},
  uControleMesaPagamentoAntecipado in 'uControleMesaPagamentoAntecipado.pas' {frmControleMesaPagamentoAntecipado},
  uMonitorpreparo in 'Monitor Preparo\uMonitorpreparo.pas' {frmMonitorpreparo},
  uVendaItemFracionadoTouch in 'uVendaItemFracionadoTouch.pas' {frmVendaItemFracionadoTouch},
  uVendaComplementoTouch in 'uVendaComplementoTouch.pas' {frmVendaComplementoTouch},
  uObservacaoTouch in 'uObservacaoTouch.pas' {frmObservacaoTouch},
  uControleNotaFiscalEntrada in 'Nfe\uControleNotaFiscalEntrada.pas' {frmControleNotaFiscalEntrada},
  uControleNotaFiscalEntradaImportacao in 'Nfe\uControleNotaFiscalEntradaImportacao.pas' {frmControleNotaFiscalEntradaImportacao},
  uControleNotaFiscalSaida in 'Nfe\uControleNotaFiscalSaida.pas' {frmControleNotaFiscalSaida},
  uDetalheNotaEntrada in 'Nfe\uDetalheNotaEntrada.pas' {frmDetalheNotaFiscalEntrada},
  uDetalheNotaEntradaDocReferenciado in 'Nfe\uDetalheNotaEntradaDocReferenciado.pas' {frmDetalheNotaEntradaDocReferenciado},
  uDetalheNotaEntradaDuplicata in 'Nfe\uDetalheNotaEntradaDuplicata.pas' {frmDetalheNotaEntradaDuplicata},
  uDetalheNotaEntradaItem in 'Nfe\uDetalheNotaEntradaItem.pas' {frmDetalheNotaEntradaItem},
  uDetalheNotaSaidaDocReferenciado in 'Nfe\uDetalheNotaSaidaDocReferenciado.pas' {frmDetalheNotaSaidaDocReferenciado},
  uDetalheNotaSaidaDuplicata in 'Nfe\uDetalheNotaSaidaDuplicata.pas' {frmDetalheNotaSaidaDuplicata},
  uDetalheNotaSaidaItem in 'Nfe\uDetalheNotaSaidaItem.pas' {frmDetalheNotaSaidaItem},
  uNFeSelecionarCertificado in 'Nfe\uNFeSelecionarCertificado.pas' {frmNFeSelecionarCertificado},
  uRelatorioNFe in 'Nfe\uRelatorioNFe.pas' {frmRelatorioNFe},
  uConsCidade in 'Consultas\uConsCidade.pas' {frmConsCidade},
  uDetalheCidade in 'Detalhes\uDetalheCidade.pas' {frmDetalheCidade},
  uVendabalcaotouchbalanca in 'uVendabalcaotouchbalanca.pas' {frmVendabalcaotouchbalanca},
  uDetalhesmesa in 'Detalhes\uDetalhesmesa.pas' {frmDetalhemesa},
  uConsSetor in 'Consultas\uConsSetor.pas' {frmConsSetor},
  uDetalheSetor in 'Detalhes\uDetalheSetor.pas' {frmDetalheSetor},
  uJuncaoefechamentocomanda in 'uJuncaoefechamentocomanda.pas' {frmJuncaoefechamentocomanda},
  uVisualizaRelatorioTexto in 'uVisualizaRelatorioTexto.pas' {frmVisualizaRelatorioTexto},
  uTransferenciaestoque in 'uTransferenciaestoque.pas' {frmTransferenciaestoque},
  uCaixaDigitaValor in 'uCaixaDigitaValor.pas' {frmCaixaDigitaValor},
  uControleCNoturnaCheckin in 'Casa Noturna\uControleCNoturnaCheckin.pas' {frmControleCNoturnaCheckin},
  uControleCNoturnaItensAcoes in 'Casa Noturna\uControleCNoturnaItensAcoes.pas' {frmControleCNoturnaItensAcoes},
  uControleCNoturnaLancamento in 'Casa Noturna\uControleCNoturnaLancamento.pas' {frmControleCNoturnaLancamento},
  uControleCNoturnaPeriodo in 'Casa Noturna\uControleCNoturnaPeriodo.pas' {frmControleCNoturnaPeriodo},
  uCadastroclientes in 'Casa Noturna\uCadastroclientes.pas' {ViewCadastroCliente},
  UCasanoturnacadastroclientes in 'Casa Noturna\UCasanoturnacadastroclientes.pas' {frmCasanoturnacadastroclientes},
  uContasareceberinclusao in 'uContasareceberinclusao.pas' {frmContasareceberinclusao},
  uImportarcomanda in 'uImportarcomanda.pas' {frmImportarcomanda},
  uLancamentocontas in 'Contas\uLancamentocontas.pas' {frmLancamentocontas},
  uLancamentocontasinclusao in 'Contas\uLancamentocontasinclusao.pas' {frmLancamentocontasinclusao},
  uConsultaIFood in 'Ifood\uConsultaIFood.pas',
  uControleIFOOD in 'Ifood\uControleIFOOD.pas' {frmControleIFOOD},
  uDetalheIFood in 'Ifood\uDetalheIFood.pas',
  uAnalisefinanceira in 'AnaliseFinanceiro\uAnalisefinanceira.pas' {frmAnalisefinanceira},
  frm_xml in 'Download NFE\frm_xml.pas' {frmxml},
  dtm_xml in 'Download NFE\dtm_xml.pas' {dtmxml: TDataModule},
  uAliquotas in 'uAliquotas.pas' {frmAliquotas},
  uTransferenciacontas in 'AnaliseFinanceiro\uTransferenciacontas.pas' {frmTransferenciacontas},
  uControlemesalancamento in 'uControlemesalancamento.pas' {frmControlemesalancamento},
  uConsIBPT in 'uConsIBPT.pas' {frmConsIBPT},
  uDetalheIBPT in 'uDetalheIBPT.pas' {frmDetalheIBPT},
  uDetalhencm in 'Detalhes\uDetalhencm.pas' {frmDetalhencm},
  uAjusteestoque in 'uAjusteestoque.pas' {frmAjusteestoque},
  uDetalheTara in 'Detalhes\uDetalheTara.pas' {frmDetalheTara},
  uImportamesa in 'uImportamesa.pas' {frmImportamesa},
  uDetalheNotaSaida in 'Nfe\uDetalheNotaSaida.pas' {frmDetalheNotaSaida},
  uDetalheNotaSaidaPagamentos in 'Nfe\uDetalheNotaSaidaPagamentos.pas' {frmDetalheNotaSaidaPagamentos},
  Comunicador in 'Geral\Comunicador.pas',
  uConsComandas in 'uConsComandas.pas' {frmConsComanda},
  uDetalhesComanda in 'Detalhes\uDetalhesComanda.pas' {frmDetalhecomanda},
  uDetalheComandaNovo in 'Detalhes\uDetalheComandaNovo.pas' {frmDetalheComandaNovo},
  uBloqueiocomanda in 'uBloqueiocomanda.pas' {frmBloqueiocomanda},
  uResumodacasa in 'uResumodacasa.pas' {frmResumodacasa},
  uImportamesaecomanda in 'uImportamesaecomanda.pas' {frmImportamesaecomanda},
  UTef in 'UTef.pas' {FTef: TDataModule},
  UGerenciaTef in 'UGerenciaTef.pas' {FGerenciaTef},
  UImpressaoCupom in 'UImpressaoCupom.pas' {FImpressaoCupom},
  uEtiquetaProduto in 'uEtiquetaProduto.pas' {frmEtiquetaProduto};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'ELITEFOOD';
  Application.CreateForm(TfrmMenu, frmMenu);
  Application.CreateForm(TFTef, FTef);
  Application.CreateForm(TfrmEtiquetaProduto, frmEtiquetaProduto);
  Application.Run;
end.
